apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The application's http port.
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: openjdk-web-basic-s2i
    application: openjdk-app
  name: openjdk-app
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    deploymentConfig: openjdk-app

