apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

Namespace: dev
bases: 
- ../../base
resources:
- bc.yml
patches:
- patch.yml
configMapGenerator:
- name: sample-cm
  files:
  - mew.txt
  options:
    disableNameSuffixHash: true
